-- MySQL Script generated by MySQL Workbench
-- dom 02 ago 2020 10:30:50 -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema file-management
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema file-management
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `file-management` ;
USE `file-management` ;

-- -----------------------------------------------------
-- Table `file-management`.`files`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `file-management`.`files` (
  `id` INT NULL,
  `name` VARCHAR(45) NULL,
  `size` INT NULL,
  `downloads` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
